services:
  apollo:
    container_name: apollo
    command: npm run dev
    build:
      context: ./apollo
      dockerfile: Dockerfile
    depends_on:
      - grpc
    environment:
      PORT: ${APOLLO_PORT}
      NODE_ENV: development
      GRPC_ADDRESS: grpc:${GRPC_PORT}
    ports:
      - ${APOLLO_PORT}:${APOLLO_PORT}
    volumes:
      - ./shared:/usr/shared
    networks:
      - public-network
    develop:
      watch:
        - action: sync
          path: ./apollo/src
          target: /usr/apollo/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./apollo/package.json

  grpc:
    container_name: grpc
    command: npm run dev
    build:
      context: ./grpc
      dockerfile: Dockerfile
    depends_on:
      - mongo
    environment:
      PORT: ${GRPC_PORT}
      MONGO_URI: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:${MONGO_PORT}/${MONGO_DATABASE}?authSource=admin
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
    volumes:
      - ./shared:/usr/shared
    networks:
      - public-network
      - database-network
    develop:
      watch:
        - action: sync
          path: ./grpc/src
          target: /usr/grpc/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./grpc/package.json

  mongo:
    container_name: mongo
    build:
      context: ./mongo
      dockerfile: Dockerfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongo-data:/data/db
    networks:
      - database-network

volumes:
  shared:
  mongo-data:

networks:
  public-network:
    driver: bridge
  database-network:
    driver: bridge 
