services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - rest
      - apollo
    environment:
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: .template
      REST_ADDRESS: rest:${REST_PORT}
      APOLLO_ADDRESS: apollo:${APOLLO_PORT}
      SWAGGER_ADDRESS: swagger:${SWAGGER_PORT}
    ports:
      - ${NGINX_IP}:${NGINX_PORT}:80
    networks:
      - public-network
      - client-proxy-network

  rest:
    container_name: rest
    command: npm run dev
    build:
      context: ./rest
      dockerfile: Dockerfile
    depends_on:
      - grpc
    environment:
      PORT: ${REST_PORT}
      NODE_END: development
      GRPC_ADDRESS: grpc:${GRPC_PORT}
    volumes:
      - ./shared:/usr/shared
    networks:
      - client-proxy-network
      - server-proxy-network

  apollo:
    container_name: apollo
    command: npm run dev
    build:
      context: ./apollo
      dockerfile: Dockerfile
    depends_on:
      - grpc
    environment:
      PORT: ${APOLLO_PORT}
      NODE_ENV: development
      GRPC_ADDRESS: grpc:${GRPC_PORT}
    volumes:
      - ./shared:/usr/shared
    networks:
      - client-proxy-network
      - server-proxy-network

  grpc:
    container_name: grpc
    command: npm run dev
    build:
      context: ./grpc
      dockerfile: Dockerfile
    depends_on:
      - mongo
    environment:
      PORT: ${GRPC_PORT}
      MONGO_URI: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:${MONGO_PORT}/${MONGO_DATABASE}?authSource=admin
    volumes:
      - ./shared:/usr/shared
    networks:
      - server-proxy-network
      - database-network

  mongo:
    container_name: mongo
    build:
      context: ./mongo
      dockerfile: Dockerfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongo-data:/data/db
    networks:
      - database-network

  swagger:
    container_name: swagger
    command: npm run dev
    build: 
      context: ./swagger
      dockerfile: Dockerfile
    depends_on:
      - nginx
    environment:
      PORT: ${SWAGGER_PORT}
      NODE_END: development
      OPENAPI_SPEC_PATH: http://localhost:${NGINX_PORT}/api/openapi.json
    volumes:
      - ./shared:/usr/shared
    networks:
      - public-network

volumes:
  shared:
  mongo-data:

networks:
  public-network:
    driver: bridge

  client-proxy-network:
    driver: bridge

  server-proxy-network:
    driver: bridge

  database-network:
    driver: bridge 
