version: '3.9'

services:
  api:
    container_name: api
    command: npm run dev
    build: 
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      PORT: ${SERVER_PORT}
      NODE_ENV: development
      MONGO_URI: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@db:${MONGO_PORT}/${MONGO_DATABASE}?authSource=admin
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - main-network
    develop:
      watch:
        - action: sync
          path: ./api/src
          target: /usr/api/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./api/package.json
  
  db:
    container_name: db
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - db-data:/data/db
    networks:
      - main-network
  
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - api
    environment:
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - "127.0.0.1:8044:80"
    networks:
      - main-network
    
volumes:
  db-data:

networks:
  main-network:
    driver: bridge 
    # TODO: make more networks so that only nginx is accessible from outside
