version: '3.9'

services:
  rest:
    container_name: rest
    command: npm run dev
    build: 
      context: ./rest
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      PORT: ${REST_PORT}
      NODE_ENV: development
      MONGO_URI: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@db:${MONGO_PORT}/${MONGO_DATABASE}?authSource=admin
      NO_APOLLO: true
    ports:
      - "${REST_PORT}:${REST_PORT}"
    volumes:
      - ./shared:/usr/shared
    networks:
      - main-network
    develop:
      watch:
        - action: sync
          path: ./rest/src
          target: /usr/rest/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./rest/package.json
  
  apollo:
    container_name: apollo
    command: npm run dev
    build:
      context: './apollo'
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      PORT: ${APOLLO_PORT}
      NODE_ENV: development
      MONGO_URI: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@db:${MONGO_PORT}/${MONGO_DATABASE}?authSource=admin
    ports:
      - "${APOLLO_PORT}:${APOLLO_PORT}"
    networks:
      - main-network
    develop:
      watch:
        - action: sync
          path: ./apollo/src
          target: /usr/apollo/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./apollo/package.json

  db:
    container_name: db
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - db-data:/data/db
    networks:
      - main-network
  
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - rest
      - apollo
    environment:
      REST_PORT: ${REST_PORT}
    ports:
      - "127.0.0.1:8044:80"
    networks:
      - main-network
    
volumes:
  shared:
  db-data:

networks:
  main-network:
    driver: bridge 
    # TODO: make more networks so that only nginx is accessible from outside
